[build]
  # 發布目錄
  publish = "."
  
  # 構建命令（如果需要）
  command = "echo 'Static site, no build needed'"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向規則
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 頭部設置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 靜態文件緩存
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JSON 文件緩存策略
[[headers]]
  for = "/works.json"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"
    Access-Control-Allow-Origin = "*"

# 404 頁面
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 表單處理（如果需要）
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# 插件配置
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://your-site.netlify.app"

